### ISSUE TITLE
Error: unable to recognize "deployments/auth.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by blackphoenix42** [googlecodelabs/orchestrate-with-kubernetes#16]
I am doing this lab in Qwiklabs - [Managing Deployments Using Kubernetes Engine](https://google.qwiklabs.com/focuses/639?parent=catalog)
When I use command `kubectl create -f deployments/auth.yaml` after changing image in `auth.yaml` to `kelseyhightower/auth:1.0.0`
I am facing this error. I had lost enough credits because of this. Please fix it asap.

**Comment by blackphoenix42** [comment]
#15 PR solved my problem.

**Comment by DhruvSondhi** [comment]
thanks for confirming sir ... appreciate it and i am happy it helped :)
