### ISSUE TITLE
api version needs to be corrected and selector line needs to be added for several yaml files

### ISSUE THREAD

**Issue by TejSahu** [googlecodelabs/orchestrate-with-kubernetes#52]
Api version needs to be corrected and selector line needs to be added for several yaml files especially here as it is creating problems while doing labs with Qwiklabs "orchestrate-with-kubernetes/kubernetes/deployments/"

**Comment by DhruvSondhi** [comment]
check pr #15

**Comment by TejSahu** [comment]
> check pr #15

Thanks man, I really wish they accept all the pull requests as well

**Comment by TejSahu** [comment]
Got the correct repo
